version: '3.8'
services:
  web:
    container_name: article-vue3-ts-web
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
